# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions



name: Node.js CI



on:

 push:

  branches: [ main ]

 pull_request:

  branches: [ main ]



jobs:

 test:

  runs-on: ubuntu-latest



  strategy:

   matrix:

    node-version: [10.x, 12.x, 14.x, 15.x]

    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/



  steps:

  - uses: actions/checkout@v2

  - name: Use Node.js ${{ matrix.node-version }}

   uses: actions/setup-node@v1

   with:

    node-version: ${{ matrix.node-version }}

  - run: npm install

  - run: npm test



 deploy:

  needs: [test]

  runs-on: ubuntu-latest

  steps:

   - uses: actions/checkout@v2

   - uses: CDNievas/heroku-action@v1.0 # This is the action

    with:

     heroku_email: ${{secrets.HEROKU_EMAIL }}

     heroku_api_key: ${{secrets.HEROKU_API_KEY}}

     heroku_app_name: "api-da-aula"
     
     procfile: "web: npm start"
